apiVersion: batch/v1
kind: Job
metadata:
  name: posts-job
spec:
  template:
    spec:
      serviceAccountName: restricted-job-sa
      initContainers:
        - name: wait-for-backend
          image: busybox
          command: ["sh", "-c", "until nc -z backend-service 80; do echo 'Waiting for backend...'; sleep 2; done;"]
      containers:
      - name: posts-container
        image: posts-image:1.0
        env:
        - name: API_URL
          value: "http://backend-service:80/posts"
        volumeMounts:
        - mountPath: "/app/data" 
          name: posts-volume
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      restartPolicy: Never
      volumes:
      - name: posts-volume
        persistentVolumeClaim:
          claimName: posts-pvc
  backoffLimit: 4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: posts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
