FROM mongo:4.4

RUN if ! id -u mongodb > /dev/null 2>&1; then \
      groupadd -g 999 mongodb && \
      useradd -u 999 -g mongodb -m -s /bin/bash mongodb; \
    fi && \
    chown -R mongodb:mongodb /data/db

USER mongodb

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["mongod"]
