FROM node:16-alpine AS build

WORKDIR /app

COPY app/package.json app/package-lock.json ./

RUN npm install --frozen-lockfile

COPY app ./

RUN npm run build

FROM nginx:alpine

RUN mkdir -p /var/cache/nginx && \
    chown -R nginx:nginx /var/cache/nginx && \
    chmod -R 755 /var/cache/nginx

COPY --from=build /app/build /usr/share/nginx/html

COPY dockerfiles/nginx.conf /etc/nginx/nginx.conf

RUN chown -R nginx:nginx /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]